---
  AWSTemplateFormatVersion: "2010-09-09"
  Description: "Create a ECS Cluster and LoadBalancer"

  Parameters:
    PublicSubnet1:
      Type: "String"
    PublicSubnet2:
      Type: "String"

  Resources:
    ECSCluster:
      Type: "AWS::ECS::Cluster"
      Properties:
        ClusterName: "TestingApp"

    LoadBalancer:
      Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
      Properties:
        Name: "ECS-Load-Balancer"
        Subnets:
          - !Ref PublicSubnet1
          - !Ref PublicSubnet2

  Outputs:
    ECSCluster: 
      Description: "ECS Cluster created"
      Value:
        Ref: "ECSCluster"

    LoadBalancerArn:
      Description: "LoadBalancer for ECS Cluster"
      Value:
        Ref: "LoadBalancer"
