---
  AWSTemplateFormatVersion: "2010-09-09"
  Description: "Create a simple VPC"

  Parameters:
    CidrBlock:
      Type: "String"
    PublicSubnet1Cidr:
      Type: "String"
    PublicSubnet2Cidr:
      Type: "String"

  Resources:
    VPC:
      Type: AWS::EC2::VPC
      Properties: 
        CidrBlock: !Ref "CidrBlock"

    PublicSubnet1:
      Type: "AWS::EC2::Subnet"
      Properties:
        VpcId:
          Ref: "VPC"
        CidrBlock: !Ref "PublicSubnet1Cidr"
        AvailabilityZone: !Select 
          - 0
          - !GetAZs
        MapPublicIpOnLaunch: "true"

    PublicSubnet2:
      Type: "AWS::EC2::Subnet"
      Properties:
        VpcId:
          Ref: "VPC"
        CidrBlock: !Ref "PublicSubnet2Cidr"
        AvailabilityZone: !Select 
          - 1
          - !GetAZs
        MapPublicIpOnLaunch: "true"

    VPCGatewayAttachment:
      Type: 'AWS::EC2::VPCGatewayAttachment'
      Properties:
        InternetGatewayId: !Ref InternetGateway
        VpcId: !Ref VPC

    InternetGateway:
      Type: 'AWS::EC2::InternetGateway'

    RouteTable:
      Type: 'AWS::EC2::RouteTable'
      Properties:
        VpcId: !Ref VPC

    RouteTableAssociation1:
      Type: 'AWS::EC2::SubnetRouteTableAssociation'
      Properties:
        SubnetId: !Ref PublicSubnet1
        RouteTableId: !Ref RouteTable

    RouteTableAssociation2:
      Type: 'AWS::EC2::SubnetRouteTableAssociation'
      Properties:
        SubnetId: !Ref PublicSubnet2
        RouteTableId: !Ref RouteTable

    InternetRoute:
      Type: 'AWS::EC2::Route'
      DependsOn: VPCGatewayAttachment
      Properties:
        GatewayId: !Ref InternetGateway
        RouteTableId: !Ref RouteTable
        DestinationCidrBlock: '0.0.0.0/0'

  Outputs:
    VPCId:
      Description: "VPCId of the created VPC"
      Value:
        Ref: "VPC"
      Export:
        Name: 'VPC'

    PublicSubnet1:
      Description: "PublicSubnet1 in AZ1"
      Value: 
        Ref: "PublicSubnet1"
      Export:
        Name: 'PublicSubnet1'

    PublicSubnet2:
      Description: "PublicSubnet2 in AZ2"
      Value: 
        Ref: "PublicSubnet2"
      Export:
        Name: 'PublicSubnet2'
